server:
  port: 9006

spring:
  application:
    name: notification-service
  output:
    ansi:
      enabled: always
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.nnson128.notificationservice.kafka.dto.EventWrapper

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/chat-apps

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    nonSecurePort: ${server.port}
    status-page-url: http://localhost:${server.port}/actuator/info
    health-check-url: http://localhost:${server.port}/actuator/health
    metadata-map:
      management.port: ${server.port}
