services:
  # KAFKA
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      # port for spring
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Cấu hình quan trọng cho dev
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

# postgres databases
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: chatapps
      POSTGRES_USER: chatapps
      POSTGRES_PASSWORD: chatapps
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

# cassandra databases
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  keycloak-mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    restart: always
    volumes:
      - ./data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    restart: always
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realms/:/opt/keycloak/data/import/
      - ./keycloak-realms:/opt/keycloak/data/export
      # - ./keycloak-realms:/opt/keycloak/data/export
      # everything in keycloaks is storage in keycloak-mysql
      # how to export json file in keycloak

#  redis:
#    image: redis:latest
#    restart: unless-stopped
#    ports:
#      - "6380:6379"
#    #      - host-port:container-port(6379)
#    volumes:
#      - ./data/redis:/data

  # CONFIGURATION SERVICE
  discovery-server:
    build: ./discovery-server
    # env_file:
    #   - ./.env
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  # api-gateway:
  #   build: ./api-gateway
  #   env_file:
  #     - ./.env.dev
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     discovery-server:
  #       condition: service_healthy      
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
  #     interval: 20s
  #     timeout: 10s
  #     retries: 5
