services:
  # ZooKeeper Service
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "*"
    ports:
      - "2181:2181"
    volumes:
      - ./data/zookeeper-data:/var/lib/zookeeper/data
      - ./data/zookeeper-log:/var/lib/zookeeper/log

  # Kafka Service
  kafka:
    image: confluentinc/cp-kafka:7.7.1
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      # start_period: 30s
    ports:
      - "29092:29092"
    volumes:
      - ./data/kafka-data:/var/lib/kafka/

# postgres databases
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: chatapps
      POSTGRES_USER: chatapps
      POSTGRES_PASSWORD: chatapps
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapps"]
      interval: 10s
      timeout: 5s
      retries: 5

# cassandra databases
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  keycloak-mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      # start_period: 30s

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: ["start-dev", "--import-realm"]
    restart: always
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"           # ← SỬA: Thêm dấu : và quotes
      KC_HTTP_ENABLED: "true"               # ← SỬA: Thêm dấu : và quotes
      KC_HOSTNAME_STRICT_HTTPS: "false"     # ← SỬA: Thêm dấu : và quotes
      KC_PROXY: edge 
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realms/:/opt/keycloak/data/import/
      - ./keycloak-realms-export:/opt/keycloak/data/export
    healthcheck:
      test: ["CMD-SHELL", "timeout 2 bash -c '</dev/tcp/localhost/8080' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      # start_period: 60s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  discovery-server:
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    # env_file:
    #   - ./.env
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
    ports:
      - 8888:8888
    # env_file:
    #   - ./.env
    environment:
      - M2_HOME=/root/.m2
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://keycloak:8080/realms/chat-apps
      - EUREKA_HOST=discovery-server
      - EUREKA_PORT=8761

    depends_on:
      discovery-server:
        condition: service_healthy      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
            
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "9005:9005"
    # env_file:
    # kiểu inject này sai
    #   - ./.env
    environment:
      MEDIA_SERVICE: media-service
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: chatapps
      POSTGRES_USER: chatapps
      POSTGRES_PASSWORD: chatapps
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: sonvipkl04@gmail.com
      MAIL_PASSWORD: "zmfw sgbw nowc pxvl"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/chat-apps
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_INSTANCE_HOSTNAME: user-service
      EUREKA_INSTANCE_STATUS_PAGE_URL: http://user-service:9005/actuator/info
      EUREKA_INSTANCE_HEALTH_CHECK_URL: http://user-service:9005/actuator/health
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9005/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      # start_period: 120s
  
  chat-service:
    build:
      context: .
      dockerfile: ./chat-service/Dockerfile
    ports:
      - "9002:9002"
    environment:
      user-service.url: http://user-service:9005
      relationship-service.url: http://relationship-service:9001
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/chat-apps
      SPRING_CASSANDRA_CONTACT_POINTS: cassandra
      SPRING_CASSANDRA_PORT: 9042
      KEYCLOAK_HOST: keycloak
      EUREKA_INSTANCE_HOSTNAME: chat-service
      EUREKA_INSTANCE_STATUS_PAGE_URL: http://chat-service:9002/actuator/info
      EUREKA_INSTANCE_HEALTH_CHECK_URL: http://chat-service:9002/actuator/health
      CASSANDRA_HOST: cassandra
      CASSANDRA_PORT: 9042
    depends_on:
      discovery-server:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -f http://localhost:9002/actuator/health || exit 1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 30
      # start_period: 120s
  
  relationship-service:
    build:
      context: .
      dockerfile: ./relationship-service/Dockerfile
    ports:
      - "9001:9001"
    environment:
      user-service.url: http://user-service:9005
      chat-service.url: http://chat-service:9002
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/chat-apps
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: chatapps
      POSTGRES_USER: chatapps
      POSTGRES_PASSWORD: chatapps
      KEYCLOAK_HOST: keycloak
      REDIS_HOST: redis
      REDIS_PORT: 6379
      EUREKA_INSTANCE_HOSTNAME: relationship-service
      EUREKA_INSTANCE_STATUS_PAGE_URL: http://relationship-service:9001/actuator/info
      EUREKA_INSTANCE_HEALTH_CHECK_URL: http://relationship-service:9001/actuator/health
      
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9001/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
      # start_period: 120s

  media-service:
    build:
      context: .
      dockerfile: ./media-service/Dockerfile
    ports:
      - "9004:9004"
    environment:
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      CLOUDINARY_CLOUD_NAME: dswdadh2n
      CLOUDINARY_API_KEY: 741574128814778
      CLOUDINARY_API_SECRET: J9XuHektVDcN5CI_3_58RmDjSoE
      KEYCLOAK_HOST: keycloak
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/chat-apps
      EUREKA_INSTANCE_HOSTNAME: media-service
      EUREKA_INSTANCE_STATUS_PAGE_URL: http://media-service:9004/actuator/info
      EUREKA_INSTANCE_HEALTH_CHECK_URL: http://media-service:9004/actuator/health
    depends_on:
      discovery-server:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9004/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "9006:9006"
    environment:
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_INSTANCE_HOSTNAME: notification-service
      EUREKA_INSTANCE_STATUS_PAGE_URL: http://notification-service:9006/actuator/info
      EUREKA_INSTANCE_HEALTH_CHECK_URL: http://notification-service:9006/actuator/health
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/chat-apps
      KEYCLOAK_HOST: keycloak
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9006/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      args:
        VITE_REACT_APP_BASE_URL: ${VITE_REACT_APP_BASE_URL:-http://localhost:8888}
    ports:
      - "5173:5173"
    depends_on:
      api-gateway:
        condition: service_healthy
      keycloak:
        condition: service_healthy
