services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    env_file:
      - ./.env.dev
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    env_file:
      - ./.env.dev
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # Cấu hình quan trọng cho dev
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0


  postgres:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_DB: chatapps
      POSTGRES_USER: chatapps
      POSTGRES_PASSWORD: chatapps
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      # - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatapps"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    env_file:
      - ./.env.dev
    healthcheck:
      test: [ "CMD", "cqlsh", "-u cassandra", "-p cassandra", "-e describe keyspaces" ]
      interval: 15s
      timeout: 10s
      retries: 10
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  keycloak-mysql:
    image: mysql:8.0
    container_name: keycloak-mysql
    restart: always
    volumes:
      - ./data/mysql_keycloak_data:/var/lib/mysql
    env_file:
      - ./.env.dev
    # environment:
    #   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #   MYSQL_DATABASE: ${MYSQL_DATABASE}
    #   MYSQL_USER: ${MYSQL_USER}
    #   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    command: [ "start-dev", "--import-realm" ]
    restart: always
    depends_on:
      keycloak-mysql:
        condition: service_healthy
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak-realms/:/opt/keycloak/data/import/
      - ./keycloak-realms:/opt/keycloak/data/export
      # - ./keycloak-realms:/opt/keycloak/data/export
      # everything in keycloaks is storage in keycloak-mysql
      # how to export json file in keycloak

  # CONFIGURATION SERVICE
  discovery-server:
    build: ./discovery-server
    env_file:
      - ./.env.dev
    ports:
      - 8761:8761
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5

  api-gateway:
    build: ./api-gateway
    env_file:
      - ./.env.dev
    ports:
      - 8888:8888
    depends_on:
      discovery-server:
        condition: service_healthy      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 30s

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "9005:9005"
    env_file:
      - ./.env.dev
    environment:
      MEDIA_SERVICE: media-service
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9005/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  media-service:
    build:
      context: ./media-service
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - "9006:9006"
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9006/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    env_file:
      - ./.env.dev
    depends_on:
      discovery-server:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8889/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "9007:9007"
    env_file:
      - ./.env.dev
    environment:
      # Server Configuration
      user-service.url: http://user-service:9005
      channel-service.url: http://channel-service:9008
    depends_on:
      discovery-server:
        condition: service_healthy
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9007/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  channel-service:
    build:
      context: ./channel-service
      dockerfile: Dockerfile
    ports:
      - "9008:9008"
    env_file:
      - ./.env.dev
    environment:
      
      # Database Configuration
      # Uses POSTGRES_* from env_file
      
      # External Services
      user-service.url: http://user-service:9005
      chat-service.url: http://chat-service:9007
      
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9008/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  friendship-service:
    build:
      context: ./friendship-service
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
    env_file:
      - ./.env.dev
    environment:
      user-service.url: http://user-service:9005
      
    depends_on:
      postgres:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9009/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
 