server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: notification-service-api
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**

#        - id: notification-service-ws
#          uri: lb:ws://notification-service
#          predicates:
#            - Path=/ws/

        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/ws/**, /api/v1/notifications/**

        - id: user-service-api
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: channel-service-api
          uri: lb://channel-service
          predicates:
            - Path=/api/v1/channels/**

        - id: chat-service-api
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/messages/**


eureka:
  client:
    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka
      defaultZone: http://localhost:8761/eureka

