server:
  port: 9001
spring:
  application:
    name: auth-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: "2Q6vY7W8xP4zR5tK9mB3nL1qJ2wE6rT8uY0vA4gH5kN7mQ9oD2aF3bV5cX1zU6tYpL3qS4wE5bH7kM9oD2aF4gJ6lN8rT0vY1xZ3cV5bN7mQ9" # Thay bằng một chuỗi bí mật của bạn
  expiration: 86400000 # 24 giờ (tính bằng mili-giây)