server:
  port: 9002
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
app:
  jwt:
    secret: MySuperSecretKeyForJWTsWhichIsLongAndSecure1234567890
