# Server
server.port=9001
spring.application.name=channel-service

# Database

# PostgreSQL: set connection timezone via options (avoid legacy Asia/Saigon)
# Encoded space -> %20
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:chatapps}
spring.datasource.username=${POSTGRES_USER:chatapps}
spring.datasource.password=${POSTGRES_PASSWORD:chatapps}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Ho_Chi_Minh

# Output
spring.output.ansi.enabled=ALWAYS

# Eureka
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}
# kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# External services
user-service.url=http://${USER_SERVICE:localhost}:9006
chat-service.url=http://${CHAT_SERVICE:localhost}:9002

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=always

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/chat-apps