# Server
server.port=9008
spring.application.name=channel-service

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_db
spring.datasource.username=postgres_user
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.generate-ddl=true

# Output
spring.output.ansi.enabled=ALWAYS

# Eureka
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}
# kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# External services
user-service.url=http://${USER_SERVICE:localhost}:9005
chat-service.url=http://${CHAT_SERVICE:localhost}:9007

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
management.endpoint.health.show-components=always