server:
  port: 9001

spring:
  application:
    name: relationship-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:chatapps}
    username: ${POSTGRES_USER:chatapps}
    password: ${POSTGRES_PASSWORD:chatapps}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
  output:
    ansi:
      enabled: ALWAYS
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
  security:
    oauth2:
      resource server:
        jwt:
          issuer-uri: http://localhost:8080/realms/chat-apps

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}

user-service:
  url: http://${USER_SERVICE:localhost}:9006

chat-service:
  url: http://${CHAT_SERVICE:localhost}:9002

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
