# Server
server.port=9006
spring.application.name=media-service

# Output
spring.output.ansi.enabled=ALWAYS

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dswdadh2n}
cloudinary.api-key=${CLOUDINARY_API_KEY:741574128814778}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:J9XuHektVDcN5CI_3_58RmDjSoE}
cloudinary.secure=true

# File upload settings
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
