# Server
server.port=9002
spring.application.name=chat-service

# Database
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
logging.level.org.springframework.data.cassandra.core.cql.CqlTemplate=DEBUG

# Output
spring.output.ansi.enabled=ALWAYS

eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}
# LoadBalancer Configuration
spring.cloud.loadbalancer.retry.enabled=false
spring.cloud.loadbalancer.cache.enabled=true

# kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Kafka Consumer Configuration
spring.kafka.consumer.group-id=chat-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.value.default.type=com.sonnguyen.chatservice.kafka.dto.EventWrapper
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.deserializer.trusted.packages=*
# application.properties
# Jackson Configuration for Java 8 Time
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=NON_NULL

# Kafka Jackson Configuration
spring.kafka.producer.properties.spring.jackson.serialization.write-dates-as-timestamps=false
spring.kafka.consumer.properties.spring.jackson.deserialization.fail-on-unknown-properties=false
spring.kafka.consumer.properties.spring.jackson.default-property-inclusion=NON_NULL

# External services
user-service.url=http://localhost:9006
channel-service.url=http://localhost:9001

# Disable default generated security user/password (dev only)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/chat-apps